# Generated by Django 5.2.11 on 2026-06-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_info',
            name='route_duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver_info',
            name='route_polyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
